name: Build browsercc
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y git ninja-build cmake curl

      - name: Increase swap memory
        run: |
          sudo fallocate -l 8G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile

      - name: Install Emscripten SDK
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install 3.1.73
          ./emsdk activate 3.1.73

      - name: Run browsercc build.sh
        run: |
          source ./emsdk/emsdk_env.sh
          chmod +x ./build.sh
          ./build.sh

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: browsercc-dist
          path: dist/
